---
name: Proc-Memory-Monitor
version: 0.0.1
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
abstract: |-
  Monitors a processes memory usage and tries to kill
  it if it starts to use too much memory.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Proc::Memory::Monitor:
    file: lib/Proc/Memory/Monitor.pm
    version: 0.0.1
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
